---
title: "Data Analysis"
author: "Hao Wang"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load data, message=FALSE, tidy=TRUE, warning=FALSE, echo=FALSE}
library(ggplot2)
library(plm)
library(dplyr)
library(tidyr)
library(stargazer)
library(pcse)
mydata <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/mydata.csv")
#add polity
mydata$polity <- mydata$e_democ - mydata$e_autoc
```



```{r}
#generate same variance, different kurtosis
set.seed(1)
y <- rt(1000, 3)
z <- rnorm(1000, 0, 3)
x <- seq(from = 1, 
         to = 1000,
         by = 1)
plotdata <- as.data.frame(cbind(x, y, z))

ggplot(data = plotdata) +
  geom_density(aes(x = y), color = "blue") +
  geom_density(aes(x = z), color = "red") +
  xlab("") +
  annotate("text", x = -7, y = 0.3, label = "Blue Line: LK = 0.24, Variance = 3") +
  annotate("text", x = -7, y = 0.28, label = "Red Line: LK = 0.12, Variance = 3") 


```

