---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: false
    fig_caption: true
    latex_engine: pdflatex
    template: ~/Dropbox/Materials/svm-r-markdown-templates/svm-latex-ms.tex
title: "Veto Player and Fiscal Policy Stability"
#thanks: "**Current version**: `r format(Sys.time(), '%B %d, %Y')`; **Corresponding author**: haowang@asu.edu."
date: "`r format(Sys.time(), '%B %d, %Y')`"
author:
- name: Hao Wang
  affiliation: Arizona State University
abstract: "Abstract is here"
keywords: "veto player, public policy"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 12pt
#spacing: double
bibliography: ~/Dropbox/Bibliography-database/Haowang.bib
biblio-style: apsr
---


# Abstract



# Argument 
Veto player $\Rightarrow$ unable to change policy rapidly $\Rightarrow$ long term incremental changes and short-term rapid changes $\Rightarrow$ punctual equilibrium [@DerekBaumgartner2016].


<!--  -->
[@TsebelisChang2004]



# Data

```{r load data, message=FALSE, tidy=TRUE, warning=FALSE}
library(readstata13)
library(MASS)
library(ggplot2)
library(plm)
library(Zelig)
library(MASS)
mydata <- read.dta13('~/Dropbox/01Research Project/Budget-Vdem/Vdem_merge.dta', nonint.factors = TRUE)
```














<!--The folowing are some examples 

```{r coefplot1, eval=FALSE, echo=FALSE, cache=FALSE, tidy=TRUE}
suppressMessages(library(Zelig))
suppressMessages(library(arm))
suppressMessages(library(coefplot))

data(voteincome)

voteincome$z.age <- arm::rescale(voteincome$age)
voteincome$z.education <- arm::rescale(voteincome$education)
voteincome$z.income <- arm::rescale(voteincome$income)

M1 <- glm(vote ~ z.age + female + z.education + z.income,
            data=voteincome, family=binomial)

coefplot(M1)
```


```{r, echo=FALSE, eval=TRUE, tidy = TRUE, cache=FALSE, fig.cap="A Coefficient Plot"}
suppressMessages(library(Zelig))
suppressMessages(library(arm))


data(voteincome)

voteincome$z.age <- arm::rescale(voteincome$age)
voteincome$z.education <- arm::rescale(voteincome$education)
voteincome$z.income <- arm::rescale(voteincome$income)

M1 <- glm(vote ~ z.age + female + z.education + z.income,
            data=voteincome, family=binomial)

arm::coefplot(M1)
```

To get `knitr` to present the results of a table, add `results="asis"` to the brackets to start the R code chunk. The ensuing output will look like this (though the table may come on the next page). 

```{r, echo=FALSE, eval=TRUE, tidy = TRUE, size="small", cache=FALSE, results="asis"}
suppressMessages(library(Zelig))
suppressMessages(library(stargazer))
suppressMessages(library(arm))

data(voteincome)

voteincome$z.age <- arm::rescale(voteincome$age)
voteincome$z.education <- arm::rescale(voteincome$education)
voteincome$z.income <- arm::rescale(voteincome$income)


M1 <- glm(vote ~ z.age + female + z.education + z.income,
            data=voteincome, family=binomial)

stargazer(M1, title="A Handsome Table", header=FALSE)
```

-->


<!-- This is for footnote: Adding `echo="FALSE"` inside the brackets to start the R chunk will omit the presentation of the R commands. It will just present the table. This provides substantial opportunity for authors in doing their analyses. Now, the analysis and presentation in the form of a polished manuscript can be effectively simultaneous.[^4]

[^4]: I'm not sure if I'm ready to commit to this myself since my workflow is still largely derived from [Rob J. Hyndman's example](http://robjhyndman.com/hyndsight/workflow-in-r/). However, *knitr* has endless potential, especially when analyses can stored in cache, saved as chunks, or loaded in the preamble of a document to reference later in the manuscript.

# Add reference
Inline refer: @Nichter2008, in bracket [@Nichter2008], suppress[Gonzales et al. -@Gonzalez-Ocantos2014] -->



<!--
# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\vspace*{-0.2in}
\noindent
-->
