---
title: "Data Analysis"
author: "Hao Wang"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Merging several sources



## Merge Data

```{r, warning=FALSE}
library(foreign)
library(dplyr)
library(readstata13)

setwd("D:/Dropbox/01Research Project/Budget-Vdem")
getwd()
GSRE <- read.dta13("GSRE_extended_1_0.dta")
VDEM <- read.dta13("V-Dem-DS-CY+Others-v6.2.dta")
colnames(VDEM)[10] <- "cowcode"
#This keeps all points from GSRE
mydata <-  merge(GSRE, VDEM, 
                 by = c("cowcode","year"), 
                 all.x = TRUE) 
```


## Subset Data

```{r}
trim <- mydata[,c("cowcode",
                  "year",
                  "country",
                  "v2x_delibdem",
                  "v2dlreason", 
                  "v2dlcommon", 
                  "v2dlcountr",                                                                "v2dlconslt", 
                  "v2dlengage", 
                  "v2xeg_eqprotec", 
                  "v2xeg_eqdr", 
                  "v2x_jucon", 
                  "v2xlg_legcon", 
                  "v2cscnsult", 
                  "v2xps_party", 
                  "v2lgqstexp",
                  "v2lginvstp",
                  "v2lgotovst", 
                  "e_competition", 
                  "e_democ", 
                  "e_autoc",
                  "v2x_corr", 
                  "v2x_pubcorr", 
                  "v2x_execorr",
                  "v2elvotbuy", 
                  "v2elirreg", 
                  "v2psprlnks",
                  "v2exbribe", 
                  "v2exembez", 
                  "v2excrptps",
                  "v2dlencmps", 
                  "e_wbgi_gee", 
                  "e_wbgi_rle",
                  "v2pepwrses", 
                  "v2pepwrsoc", 
                  "v2elreggov",
                  "v2elrgpwr", 
                  "v2ellocgov", 
                  "v2ellocpwr",
                  "v2x_feduni", 
                  "e_dpi_author", 
                  "v2mecenefm",
                  "v2mecenefi",
                  "e_peaveduc", 
                  "e_migdppcln",
                  "e_migdpgro", 
                  "e_peginiwi", 
                  "e_reserves_billions",
                  "e_Total_Oil_Income_PC", 
                  "e_Fiscal_Reliance", "e_miinteco",
                  "e_miinterc", 
                  "e_Civil_War", 
                  "e_h_polcon3", 
                  "e_h_polcon5",
                  
                  "expend_security_EXP",  
                  "expenddefence_EXP", 
                  "exp_public_order_EXP", 
                  "wagessalaries_EXP",
                  "subpentrans_EXP", 
                  "pensions_EXP", 
                  "total_welfare_EXP",                                                         "education_EXP", 
                  "health_EXP", 
                  "social_protection_EXP", 
                  "housing_EXP", 
                  "owelfarespend_EXP", 
                  "expend_security_GDPGSRE",                                                   "expenddefence_GDPGSRE",
                  "exp_public_order_GDPGSRE", 
                  "wagessalaries_GDPGSRE", 
                  "subpentrans_GDPGSRE", 
                  "pensions_GDPGSRE", 
                  "total_welfare_GDPGSRE",                                                     "education_GDPGSRE", 
                  "health_GDPGSRE", 
                  "social_protection_GDPGSRE", 
                  "housing_GDPGSRE", 
                  "owelfarespend_GDPGSRE" , 
                  "expend_security",
                  "expenddefence", 
                  "exp_public_order", 
                  "wagessalaries",
                  "subpentrans", 
                  "pensions", 
                  "total_welfare",
                  "education", 
                  "health",
                  "social_protection", 
                  "housing",
                  "owelfarespend",
                  
                  "e_v2x_polyarchy_3C",
                  "e_v2x_polyarchy_4C",
                  "e_v2x_polyarchy_5C",
                  "e_v2x_api_3C",
                  "e_v2x_api_4C",
                  "e_v2x_api_5C",
                  "e_v2x_EDcomp_thick_3C",
                  "e_v2x_EDcomp_thick_4C",
                  "e_v2x_EDcomp_thick_5C",
                  "e_v2x_libdem_3C",
                  "e_v2x_libdem_4C",
                  "e_v2x_libdem_5C"
                  )]
names(trim)
```




# Clean Some Mis-coded items
```{r}
library(dplyr)
mydata <- trim
#mydata <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/vdem-merge.csv")
#some cleaning
#code polity -88 -66 -77 to na
mydata <-
  mydata %>%
  mutate(e_democ = replace(e_democ, e_democ == -88, NA), 
         e_autoc = replace(e_autoc, e_autoc == -88, NA)) %>%
  mutate(e_democ = replace(e_democ, e_democ == -77, NA), 
         e_autoc = replace(e_autoc, e_autoc == -77, NA)) %>%
  mutate(e_democ = replace(e_democ, e_democ == -66, NA), 
         e_autoc = replace(e_autoc, e_autoc == -66, NA)) 
mydata <- select(mydata, -subpentrans_EXP, -subpentrans_GDPGSRE)
#get rid of two annoying observations 
newdata <- filter(mydata, wagessalaries_EXP > 1)
mydata <- setdiff(mydata, newdata)

write.csv(x = mydata, row.names = FALSE, file = "vdem-merge-clean.csv")
```





# Adding DV into mydata frame

without multiple imputation

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
mydata <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/vdem-merge-clean.csv")
#This code is using the existing percentage index
dv2 <- select(mydata, c(56:66), cowcode, year)
dv2 <- select(dv2, -pensions_EXP)


#replace NA to 0. 
dv2[is.na(dv2)] <- 0


#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(lag.expend_security_EXP = lag(expend_security_EXP, 1), 
           lag.expenddefence_EXP = lag(expenddefence_EXP, 1),
           lag.exp_public_order_EXP = lag(exp_public_order_EXP, 1), 
           lag.wagessalaries_EXP = lag(wagessalaries_EXP, 1), 
           lag.total_welfare_EXP = lag(total_welfare_EXP, 1), 
           lag.education_EXP = lag(education_EXP, 1), 
           lag.health_EXP = lag(health_EXP, 1),
           lag.social_protection_EXP = lag(social_protection_EXP, 1),
           lag.housing_EXP = lag(housing_EXP, 1), 
           lag.owelfarespend_EXP = lag(owelfarespend_EXP, 1))

#calculate stability index
attach(dv2)
yb <- (expend_security_EXP - lag.expend_security_EXP)^2 +
     (expenddefence_EXP - lag.expenddefence_EXP)^2 +
     (exp_public_order_EXP - lag.exp_public_order_EXP)^2 +
     (wagessalaries_EXP - lag.wagessalaries_EXP)^2 +
     (total_welfare_EXP - lag.total_welfare_EXP)^2 +
     (education_EXP - lag.education_EXP)^2 +
     (health_EXP - lag.health_EXP)^2 +
     (social_protection_EXP - lag.social_protection_EXP)^2 +
     (housing_EXP - lag.housing_EXP)^2 +
     (owelfarespend_EXP - lag.owelfarespend_EXP)^2


#attach to data
mydata$stability_0 <- sqrt(yb)
#recode 0 to missing
mydata$stability_0[mydata$stability_0 == 0] <- NA


# Multiple Imputation : based on raw percentage
library(Amelia)

rawp <- select(mydata, 
               cowcode, 
               year, 
               c(56:66))
names(rawp)
summary(rawp)
#get rid of pension
rawp <- select(rawp, -pensions_EXP)

set.seed(3)
a.out <- amelia(rawp, 
                ts = "year", 
                cs = "cowcode", 
                m = 5)
write.amelia(a.out, 
             row.names = FALSE,
             format  = "csv", 
             file.stem = "imp")
```


# Multiple imputation: based on raw expenditure percentage

```{r}
library(dplyr)
imp1 <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/imp1.csv")
imp2 <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/imp2.csv")
imp3 <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/imp3.csv")
imp4 <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/imp4.csv")
imp5 <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/imp5.csv") 

#-----------------------------------------------------------------------------------------------
dv2 <- imp1
#replace NA to 0. 
dv2[is.na(dv2)] <- 0


#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(lag.expend_security_EXP = lag(expend_security_EXP, 1), 
           lag.expenddefence_EXP = lag(expenddefence_EXP, 1),
           lag.exp_public_order_EXP = lag(exp_public_order_EXP, 1), 
           lag.wagessalaries_EXP = lag(wagessalaries_EXP, 1), 
           lag.total_welfare_EXP = lag(total_welfare_EXP, 1), 
           lag.education_EXP = lag(education_EXP, 1), 
           lag.health_EXP = lag(health_EXP, 1),
           lag.social_protection_EXP = lag(social_protection_EXP, 1),
           lag.housing_EXP = lag(housing_EXP, 1), 
           lag.owelfarespend_EXP = lag(owelfarespend_EXP, 1))

#calculate stability index
attach(dv2)
yb <- (expend_security_EXP - lag.expend_security_EXP)^2 +
     (expenddefence_EXP - lag.expenddefence_EXP)^2 +
     (exp_public_order_EXP - lag.exp_public_order_EXP)^2 +
     (wagessalaries_EXP - lag.wagessalaries_EXP)^2 +
     (total_welfare_EXP - lag.total_welfare_EXP)^2 +
     (education_EXP - lag.education_EXP)^2 +
     (health_EXP - lag.health_EXP)^2 +
     (social_protection_EXP - lag.social_protection_EXP)^2 +
     (housing_EXP - lag.housing_EXP)^2 +
     (owelfarespend_EXP - lag.owelfarespend_EXP)^2


#attach to data
mydata$stability_1 <- sqrt(yb)
#recode 0 to missing
mydata$stability_1[mydata$stability_1 == 0] <- NA

#--------------------------------------------------------------------------
dv2 <- imp2
#replace NA to 0. 
dv2[is.na(dv2)] <- 0


#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(lag.expend_security_EXP = lag(expend_security_EXP, 1), 
           lag.expenddefence_EXP = lag(expenddefence_EXP, 1),
           lag.exp_public_order_EXP = lag(exp_public_order_EXP, 1), 
           lag.wagessalaries_EXP = lag(wagessalaries_EXP, 1), 
           lag.total_welfare_EXP = lag(total_welfare_EXP, 1), 
           lag.education_EXP = lag(education_EXP, 1), 
           lag.health_EXP = lag(health_EXP, 1),
           lag.social_protection_EXP = lag(social_protection_EXP, 1),
           lag.housing_EXP = lag(housing_EXP, 1), 
           lag.owelfarespend_EXP = lag(owelfarespend_EXP, 1))

#calculate stability index
attach(dv2)
yb <- (expend_security_EXP - lag.expend_security_EXP)^2 +
     (expenddefence_EXP - lag.expenddefence_EXP)^2 +
     (exp_public_order_EXP - lag.exp_public_order_EXP)^2 +
     (wagessalaries_EXP - lag.wagessalaries_EXP)^2 +
     (total_welfare_EXP - lag.total_welfare_EXP)^2 +
     (education_EXP - lag.education_EXP)^2 +
     (health_EXP - lag.health_EXP)^2 +
     (social_protection_EXP - lag.social_protection_EXP)^2 +
     (housing_EXP - lag.housing_EXP)^2 +
     (owelfarespend_EXP - lag.owelfarespend_EXP)^2


#attach to data
mydata$stability_2 <- sqrt(yb)
#recode 0 to missing
mydata$stability_2[mydata$stability_2 == 0] <- NA

#--------------------------------------------------------------------------
dv2 <- imp3
#replace NA to 0. 
dv2[is.na(dv2)] <- 0


#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(lag.expend_security_EXP = lag(expend_security_EXP, 1), 
           lag.expenddefence_EXP = lag(expenddefence_EXP, 1),
           lag.exp_public_order_EXP = lag(exp_public_order_EXP, 1), 
           lag.wagessalaries_EXP = lag(wagessalaries_EXP, 1), 
           lag.total_welfare_EXP = lag(total_welfare_EXP, 1), 
           lag.education_EXP = lag(education_EXP, 1), 
           lag.health_EXP = lag(health_EXP, 1),
           lag.social_protection_EXP = lag(social_protection_EXP, 1),
           lag.housing_EXP = lag(housing_EXP, 1), 
           lag.owelfarespend_EXP = lag(owelfarespend_EXP, 1))

#calculate stability index
attach(dv2)
yb <- (expend_security_EXP - lag.expend_security_EXP)^2 +
     (expenddefence_EXP - lag.expenddefence_EXP)^2 +
     (exp_public_order_EXP - lag.exp_public_order_EXP)^2 +
     (wagessalaries_EXP - lag.wagessalaries_EXP)^2 +
     (total_welfare_EXP - lag.total_welfare_EXP)^2 +
     (education_EXP - lag.education_EXP)^2 +
     (health_EXP - lag.health_EXP)^2 +
     (social_protection_EXP - lag.social_protection_EXP)^2 +
     (housing_EXP - lag.housing_EXP)^2 +
     (owelfarespend_EXP - lag.owelfarespend_EXP)^2


#attach to data
mydata$stability_3 <- sqrt(yb)
#recode 0 to missing
mydata$stability_3[mydata$stability_3 == 0] <- NA

#--------------------------------------------------------------------------
dv2 <- imp4
#replace NA to 0. 
dv2[is.na(dv2)] <- 0


#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(lag.expend_security_EXP = lag(expend_security_EXP, 1), 
           lag.expenddefence_EXP = lag(expenddefence_EXP, 1),
           lag.exp_public_order_EXP = lag(exp_public_order_EXP, 1), 
           lag.wagessalaries_EXP = lag(wagessalaries_EXP, 1), 
           lag.total_welfare_EXP = lag(total_welfare_EXP, 1), 
           lag.education_EXP = lag(education_EXP, 1), 
           lag.health_EXP = lag(health_EXP, 1),
           lag.social_protection_EXP = lag(social_protection_EXP, 1),
           lag.housing_EXP = lag(housing_EXP, 1), 
           lag.owelfarespend_EXP = lag(owelfarespend_EXP, 1))

#calculate stability index
attach(dv2)
yb <- (expend_security_EXP - lag.expend_security_EXP)^2 +
     (expenddefence_EXP - lag.expenddefence_EXP)^2 +
     (exp_public_order_EXP - lag.exp_public_order_EXP)^2 +
     (wagessalaries_EXP - lag.wagessalaries_EXP)^2 +
     (total_welfare_EXP - lag.total_welfare_EXP)^2 +
     (education_EXP - lag.education_EXP)^2 +
     (health_EXP - lag.health_EXP)^2 +
     (social_protection_EXP - lag.social_protection_EXP)^2 +
     (housing_EXP - lag.housing_EXP)^2 +
     (owelfarespend_EXP - lag.owelfarespend_EXP)^2


#attach to data
mydata$stability_4 <- sqrt(yb)
#recode 0 to missing
mydata$stability_4[mydata$stability_4 == 0] <- NA

#--------------------------------------------------------------------------
dv2 <- imp5
#replace NA to 0. 
dv2[is.na(dv2)] <- 0


#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(lag.expend_security_EXP = lag(expend_security_EXP, 1), 
           lag.expenddefence_EXP = lag(expenddefence_EXP, 1),
           lag.exp_public_order_EXP = lag(exp_public_order_EXP, 1), 
           lag.wagessalaries_EXP = lag(wagessalaries_EXP, 1), 
           lag.total_welfare_EXP = lag(total_welfare_EXP, 1), 
           lag.education_EXP = lag(education_EXP, 1), 
           lag.health_EXP = lag(health_EXP, 1),
           lag.social_protection_EXP = lag(social_protection_EXP, 1),
           lag.housing_EXP = lag(housing_EXP, 1), 
           lag.owelfarespend_EXP = lag(owelfarespend_EXP, 1))

#calculate stability index
attach(dv2)
yb <- (expend_security_EXP - lag.expend_security_EXP)^2 +
     (expenddefence_EXP - lag.expenddefence_EXP)^2 +
     (exp_public_order_EXP - lag.exp_public_order_EXP)^2 +
     (wagessalaries_EXP - lag.wagessalaries_EXP)^2 +
     (total_welfare_EXP - lag.total_welfare_EXP)^2 +
     (education_EXP - lag.education_EXP)^2 +
     (health_EXP - lag.health_EXP)^2 +
     (social_protection_EXP - lag.social_protection_EXP)^2 +
     (housing_EXP - lag.housing_EXP)^2 +
     (owelfarespend_EXP - lag.owelfarespend_EXP)^2


#attach to data
mydata$stability_5 <- sqrt(yb)
#recode 0 to missing
mydata$stability_5[mydata$stability_5 == 0] <- NA


#--------------------------------------------------------------------------
#export to doable file
write.csv(x = mydata, row.names = FALSE, file = "mydata.csv")
```









# Calculate LK score 


```{r}
library(Lmoments)
library(reshape2)
library(dplyr)
#-------------------------------------
mydata <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/mydata.csv")
#-------------------------------------
#collapse original data to mean-substraction
d <- mydata %>%
  group_by(cowcode, country) %>%
  summarise_each(funs(mean(., na.rm = TRUE)))
#get rid of the missing
d <- d[!(is.na(d$stability_0)),]

imp0 <- select(mydata, cowcode, year, c(56:66)) 
imp0 <- select(imp0, -pensions_EXP)


#--------------------------------------------------------------------------
dv2 <- imp0
#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(diff.expend_security_EXP = expend_security_EXP - lag(expend_security_EXP, 1), 
           diff.expenddefence_EXP = expenddefence_EXP - lag(expenddefence_EXP, 1),
           diff.exp_public_order_EXP = exp_public_order_EXP - lag(exp_public_order_EXP, 1), 
           diff.wagessalaries_EXP = wagessalaries_EXP - lag(wagessalaries_EXP, 1), 
           diff.total_welfare_EXP = total_welfare_EXP - lag(total_welfare_EXP, 1), 
           diff.education_EXP = education_EXP - lag(education_EXP, 1), 
           diff.health_EXP = health_EXP - lag(health_EXP, 1),
           diff.social_protection_EXP = social_protection_EXP - lag(social_protection_EXP, 1),
           diff.housing_EXP = housing_EXP - lag(housing_EXP, 1), 
           diff.owelfarespend_EXP = owelfarespend_EXP - lag(owelfarespend_EXP, 1))

dv2 <- select(dv2, cowcode, c(13:22))

aql <- melt(dv2, id.vars = c("cowcode"))
aql <- na.omit(aql)
a <- tapply(aql$value, aql$cowcode, function(x) Lcoefs(x))
#a <- tapply(aql$value, aql$cowcode, function(x) Lmoments(x, returnobject = FALSE))
b <- as.data.frame(matrix(unlist(a), nrow = 4))
#transpose, this is the LK score
y_lk0 <- t(b)[, 4]
d$y_lk0 <- y_lk0

#------------------------------------------------------------------------------

imp1 <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/imp1.csv")

dv2 <- imp1
#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(diff.expend_security_EXP = expend_security_EXP - lag(expend_security_EXP, 1), 
           diff.expenddefence_EXP = expenddefence_EXP - lag(expenddefence_EXP, 1),
           diff.exp_public_order_EXP = exp_public_order_EXP - lag(exp_public_order_EXP, 1), 
           diff.wagessalaries_EXP = wagessalaries_EXP - lag(wagessalaries_EXP, 1), 
           diff.total_welfare_EXP = total_welfare_EXP - lag(total_welfare_EXP, 1), 
           diff.education_EXP = education_EXP - lag(education_EXP, 1), 
           diff.health_EXP = health_EXP - lag(health_EXP, 1),
           diff.social_protection_EXP = social_protection_EXP - lag(social_protection_EXP, 1),
           diff.housing_EXP = housing_EXP - lag(housing_EXP, 1), 
           diff.owelfarespend_EXP = owelfarespend_EXP - lag(owelfarespend_EXP, 1))

dv2 <- select(dv2, cowcode, c(13:22))

aql <- melt(dv2, id.vars = c("cowcode"))
aql <- na.omit(aql)
a <- tapply(aql$value, aql$cowcode, function(x) Lcoefs(x))
b <- as.data.frame(matrix(unlist(a), nrow = 4))
#transpose, this is the LK score
y_lk1 <- t(b)[, 4]
d$y_lk1 <- y_lk1

#------------------------------------------------------------------------------------


imp2 <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/imp2.csv")

dv2 <- imp2
#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(diff.expend_security_EXP = expend_security_EXP - lag(expend_security_EXP, 1), 
           diff.expenddefence_EXP = expenddefence_EXP - lag(expenddefence_EXP, 1),
           diff.exp_public_order_EXP = exp_public_order_EXP - lag(exp_public_order_EXP, 1), 
           diff.wagessalaries_EXP = wagessalaries_EXP - lag(wagessalaries_EXP, 1), 
           diff.total_welfare_EXP = total_welfare_EXP - lag(total_welfare_EXP, 1), 
           diff.education_EXP = education_EXP - lag(education_EXP, 1), 
           diff.health_EXP = health_EXP - lag(health_EXP, 1),
           diff.social_protection_EXP = social_protection_EXP - lag(social_protection_EXP, 1),
           diff.housing_EXP = housing_EXP - lag(housing_EXP, 1), 
           diff.owelfarespend_EXP = owelfarespend_EXP - lag(owelfarespend_EXP, 1))

dv2 <- select(dv2, cowcode, c(13:22))

aql <- melt(dv2, id.vars = c("cowcode"))
aql <- na.omit(aql)
a <- tapply(aql$value, aql$cowcode, function(x) Lcoefs(x))
b <- as.data.frame(matrix(unlist(a), nrow = 4))
#transpose, this is the LK score
y_lk2 <- t(b)[, 4]
d$y_lk2 <- y_lk2

#------------------------------------------------------------------------------------


imp3 <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/imp3.csv")

dv2 <- imp3
#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(diff.expend_security_EXP = expend_security_EXP - lag(expend_security_EXP, 1), 
           diff.expenddefence_EXP = expenddefence_EXP - lag(expenddefence_EXP, 1),
           diff.exp_public_order_EXP = exp_public_order_EXP - lag(exp_public_order_EXP, 1), 
           diff.wagessalaries_EXP = wagessalaries_EXP - lag(wagessalaries_EXP, 1), 
           diff.total_welfare_EXP = total_welfare_EXP - lag(total_welfare_EXP, 1), 
           diff.education_EXP = education_EXP - lag(education_EXP, 1), 
           diff.health_EXP = health_EXP - lag(health_EXP, 1),
           diff.social_protection_EXP = social_protection_EXP - lag(social_protection_EXP, 1),
           diff.housing_EXP = housing_EXP - lag(housing_EXP, 1), 
           diff.owelfarespend_EXP = owelfarespend_EXP - lag(owelfarespend_EXP, 1))

dv2 <- select(dv2, cowcode, c(13:22))

aql <- melt(dv2, id.vars = c("cowcode"))
aql <- na.omit(aql)
a <- tapply(aql$value, aql$cowcode, function(x) Lcoefs(x))
b <- as.data.frame(matrix(unlist(a), nrow = 4))
#transpose, this is the LK score
y_lk3 <- t(b)[, 4]
d$y_lk3 <- y_lk3

#------------------------------------------------------------------------------------


imp4 <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/imp4.csv")

dv2 <- imp4
#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(diff.expend_security_EXP = expend_security_EXP - lag(expend_security_EXP, 1), 
           diff.expenddefence_EXP = expenddefence_EXP - lag(expenddefence_EXP, 1),
           diff.exp_public_order_EXP = exp_public_order_EXP - lag(exp_public_order_EXP, 1), 
           diff.wagessalaries_EXP = wagessalaries_EXP - lag(wagessalaries_EXP, 1), 
           diff.total_welfare_EXP = total_welfare_EXP - lag(total_welfare_EXP, 1), 
           diff.education_EXP = education_EXP - lag(education_EXP, 1), 
           diff.health_EXP = health_EXP - lag(health_EXP, 1),
           diff.social_protection_EXP = social_protection_EXP - lag(social_protection_EXP, 1),
           diff.housing_EXP = housing_EXP - lag(housing_EXP, 1), 
           diff.owelfarespend_EXP = owelfarespend_EXP - lag(owelfarespend_EXP, 1))

dv2 <- select(dv2, cowcode, c(13:22))

aql <- melt(dv2, id.vars = c("cowcode"))
aql <- na.omit(aql)
a <- tapply(aql$value, aql$cowcode, function(x) Lcoefs(x))
b <- as.data.frame(matrix(unlist(a), nrow = 4))
#transpose, this is the LK score
y_lk4 <- t(b)[, 4]
d$y_lk4 <- y_lk4

#------------------------------------------------------------------------------------


imp5 <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/imp5.csv")

dv2 <- imp5
#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(diff.expend_security_EXP = expend_security_EXP - lag(expend_security_EXP, 1), 
           diff.expenddefence_EXP = expenddefence_EXP - lag(expenddefence_EXP, 1),
           diff.exp_public_order_EXP = exp_public_order_EXP - lag(exp_public_order_EXP, 1), 
           diff.wagessalaries_EXP = wagessalaries_EXP - lag(wagessalaries_EXP, 1), 
           diff.total_welfare_EXP = total_welfare_EXP - lag(total_welfare_EXP, 1), 
           diff.education_EXP = education_EXP - lag(education_EXP, 1), 
           diff.health_EXP = health_EXP - lag(health_EXP, 1),
           diff.social_protection_EXP = social_protection_EXP - lag(social_protection_EXP, 1),
           diff.housing_EXP = housing_EXP - lag(housing_EXP, 1), 
           diff.owelfarespend_EXP = owelfarespend_EXP - lag(owelfarespend_EXP, 1))

dv2 <- select(dv2, cowcode, c(13:22))

aql <- melt(dv2, id.vars = c("cowcode"))
aql <- na.omit(aql)
a <- tapply(aql$value, aql$cowcode, function(x) Lcoefs(x))
b <- as.data.frame(matrix(unlist(a), nrow = 4))
#transpose, this is the LK score
y_lk5 <- t(b)[, 4]
d$y_lk5 <- y_lk5

#------------------------------------------------------------------------------------

write.csv(x = d, row.names = FALSE, file = "LKscore.csv")
```




# LK Scores for democracy and autocracies

```{r}
mydata <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/mydata.csv")
GSRE <- select(mydata, c(56:66))
#if listwise deletion... 
GSRE <- na.omit(GSRE)
dim(GSRE)


#recode democracy index based on ordered scale
mydata$demo_order <- mydata$e_v2x_polyarchy_3C
mydata$demo_order[mydata$demo_order == 0] <- 0
mydata$demo_order[mydata$demo_order == 0.5] <- 1
mydata$demo_order[mydata$demo_order == 1] <- 2
mydata$demo_order <- as.factor(mydata$demo_order)



#collapse original data to mean-substraction
d <- mydata %>%
  group_by(cowcode, country) %>%
  summarise_each(funs(mean(., na.rm = TRUE)))
#get rid of the missing
d <- d[!(is.na(d$stability_0)),]

imp0 <- select(mydata, cowcode, year, c(56:66)) 
imp0 <- select(imp0, -pensions_EXP)


#--------------------------------------------------------------------------
dv2 <- imp0
#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(diff.expend_security_EXP = expend_security_EXP - lag(expend_security_EXP, 1), 
           diff.expenddefence_EXP = expenddefence_EXP - lag(expenddefence_EXP, 1),
           diff.exp_public_order_EXP = exp_public_order_EXP - lag(exp_public_order_EXP, 1), 
           diff.wagessalaries_EXP = wagessalaries_EXP - lag(wagessalaries_EXP, 1), 
           diff.total_welfare_EXP = total_welfare_EXP - lag(total_welfare_EXP, 1), 
           diff.education_EXP = education_EXP - lag(education_EXP, 1), 
           diff.health_EXP = health_EXP - lag(health_EXP, 1),
           diff.social_protection_EXP = social_protection_EXP - lag(social_protection_EXP, 1),
           diff.housing_EXP = housing_EXP - lag(housing_EXP, 1), 
           diff.owelfarespend_EXP = owelfarespend_EXP - lag(owelfarespend_EXP, 1))

dv2 <- select(dv2, cowcode, c(13:22))

aql <- melt(dv2, id.vars = c("cowcode"))
aql <- na.omit(aql)
a <- tapply(aql$value, aql$cowcode, function(x) Lcoefs(x))
#a <- tapply(aql$value, aql$cowcode, function(x) Lmoments(x, returnobject = FALSE))
b <- as.data.frame(matrix(unlist(a), nrow = 4))
#transpose, this is the LK score
y_lk0 <- t(b)[, 4]
d$y_lk0 <- y_lk0

```











<!-- seems unrelevant for the moment

# Recalculating Stability and LK score

## add stability_x_aj to mydata.csv

```{r, message=FALSE}
library(dplyr)
library(Lmoments)
mydata <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/mydata.csv")

```




## without multiple imputation
```{r, message=FALSE}
dv2 <- select(mydata, c(56:66), cowcode, year)
#get rid of wage 
dv2 <- select(dv2, -pensions_EXP, -wagessalaries_EXP)


#replace NA to 0. 
dv2[is.na(dv2)] <- 0

#
#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(lag.expend_security_EXP = lag(expend_security_EXP, 1), 
           lag.expenddefence_EXP = lag(expenddefence_EXP, 1),
           lag.exp_public_order_EXP = lag(exp_public_order_EXP, 1), 
           lag.total_welfare_EXP = lag(total_welfare_EXP, 1), 
           lag.education_EXP = lag(education_EXP, 1), 
           lag.health_EXP = lag(health_EXP, 1),
           lag.social_protection_EXP = lag(social_protection_EXP, 1),
           lag.housing_EXP = lag(housing_EXP, 1), 
           lag.owelfarespend_EXP = lag(owelfarespend_EXP, 1))

#calculate stability index
attach(dv2)
yb <- (expend_security_EXP - lag.expend_security_EXP)^2 +
     (expenddefence_EXP - lag.expenddefence_EXP)^2 +
     (exp_public_order_EXP - lag.exp_public_order_EXP)^2 +
     (total_welfare_EXP - lag.total_welfare_EXP)^2 +
     (education_EXP - lag.education_EXP)^2 +
     (health_EXP - lag.health_EXP)^2 +
     (social_protection_EXP - lag.social_protection_EXP)^2 +
     (housing_EXP - lag.housing_EXP)^2 +
     (owelfarespend_EXP - lag.owelfarespend_EXP)^2


#attach to data
mydata$stability_0_aj <- sqrt(yb)
#recode 0 to missing
mydata$stability_0_aj[mydata$stability_0_aj == 0] <- NA
```



# Multiple imputation: without wage index

```{r, message=FALSE, warning=FALSE}
library(dplyr)
imp1 <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/imp1.csv")
imp2 <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/imp2.csv")
imp3 <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/imp3.csv")
imp4 <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/imp4.csv")
imp5 <- read.csv("https://raw.githubusercontent.com/haowang666/Veto-Fiscal/master/data/imp5.csv") 

#-----------------------------------------------------------------------------------------------
dv2 <- imp1
#replace NA to 0. 
dv2[is.na(dv2)] <-0


#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(lag.expend_security_EXP = lag(expend_security_EXP, 1), 
           lag.expenddefence_EXP = lag(expenddefence_EXP, 1),
           lag.exp_public_order_EXP = lag(exp_public_order_EXP, 1), 
           lag.total_welfare_EXP = lag(total_welfare_EXP, 1), 
           lag.education_EXP = lag(education_EXP, 1), 
           lag.health_EXP = lag(health_EXP, 1),
           lag.social_protection_EXP = lag(social_protection_EXP, 1),
           lag.housing_EXP = lag(housing_EXP, 1), 
           lag.owelfarespend_EXP = lag(owelfarespend_EXP, 1))

#calculate stability index
attach(dv2)
yb <- (expend_security_EXP - lag.expend_security_EXP)^2 +
     (expenddefence_EXP - lag.expenddefence_EXP)^2 +
     (exp_public_order_EXP - lag.exp_public_order_EXP)^2 +
     (total_welfare_EXP - lag.total_welfare_EXP)^2 +
     (education_EXP - lag.education_EXP)^2 +
     (health_EXP - lag.health_EXP)^2 +
     (social_protection_EXP - lag.social_protection_EXP)^2 +
     (housing_EXP - lag.housing_EXP)^2 +
     (owelfarespend_EXP - lag.owelfarespend_EXP)^2


#attach to data
mydata$stability_1_aj <- sqrt(yb)
#recode 0 to missing
mydata$stability_1_aj[mydata$stability_1_aj == 0] <- NA

#--------------------------------------------------------------------------
dv2 <- imp2
#replace NA to 0. 
dv2[is.na(dv2)] <- 0


#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(lag.expend_security_EXP = lag(expend_security_EXP, 1), 
           lag.expenddefence_EXP = lag(expenddefence_EXP, 1),
           lag.exp_public_order_EXP = lag(exp_public_order_EXP, 1), 
           lag.total_welfare_EXP = lag(total_welfare_EXP, 1), 
           lag.education_EXP = lag(education_EXP, 1), 
           lag.health_EXP = lag(health_EXP, 1),
           lag.social_protection_EXP = lag(social_protection_EXP, 1),
           lag.housing_EXP = lag(housing_EXP, 1), 
           lag.owelfarespend_EXP = lag(owelfarespend_EXP, 1))

#calculate stability index
attach(dv2)
yb <- (expend_security_EXP - lag.expend_security_EXP)^2 +
     (expenddefence_EXP - lag.expenddefence_EXP)^2 +
     (exp_public_order_EXP - lag.exp_public_order_EXP)^2 +
     (total_welfare_EXP - lag.total_welfare_EXP)^2 +
     (education_EXP - lag.education_EXP)^2 +
     (health_EXP - lag.health_EXP)^2 +
     (social_protection_EXP - lag.social_protection_EXP)^2 +
     (housing_EXP - lag.housing_EXP)^2 +
     (owelfarespend_EXP - lag.owelfarespend_EXP)^2


#attach to data
mydata$stability_2_aj <- sqrt(yb)
#recode 0 to missing
mydata$stability_2_aj[mydata$stability_2_aj == 0] <- NA

#--------------------------------------------------------------------------
dv2 <- imp3
#replace NA to 0. 
dv2[is.na(dv2)] <- 0


#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(lag.expend_security_EXP = lag(expend_security_EXP, 1), 
           lag.expenddefence_EXP = lag(expenddefence_EXP, 1),
           lag.exp_public_order_EXP = lag(exp_public_order_EXP, 1), 
           lag.total_welfare_EXP = lag(total_welfare_EXP, 1), 
           lag.education_EXP = lag(education_EXP, 1), 
           lag.health_EXP = lag(health_EXP, 1),
           lag.social_protection_EXP = lag(social_protection_EXP, 1),
           lag.housing_EXP = lag(housing_EXP, 1), 
           lag.owelfarespend_EXP = lag(owelfarespend_EXP, 1))

#calculate stability index
attach(dv2)
yb <- (expend_security_EXP - lag.expend_security_EXP)^2 +
     (expenddefence_EXP - lag.expenddefence_EXP)^2 +
     (exp_public_order_EXP - lag.exp_public_order_EXP)^2 +
     (total_welfare_EXP - lag.total_welfare_EXP)^2 +
     (education_EXP - lag.education_EXP)^2 +
     (health_EXP - lag.health_EXP)^2 +
     (social_protection_EXP - lag.social_protection_EXP)^2 +
     (housing_EXP - lag.housing_EXP)^2 +
     (owelfarespend_EXP - lag.owelfarespend_EXP)^2


#attach to data
mydata$stability_3_aj <- sqrt(yb)
#recode 0 to missing
mydata$stability_3_aj[mydata$stability_3_aj == 0] <- NA

#--------------------------------------------------------------------------
dv2 <- imp4
#replace NA to 0. 
dv2[is.na(dv2)] <- 0


#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(lag.expend_security_EXP = lag(expend_security_EXP, 1), 
           lag.expenddefence_EXP = lag(expenddefence_EXP, 1),
           lag.exp_public_order_EXP = lag(exp_public_order_EXP, 1), 
           lag.total_welfare_EXP = lag(total_welfare_EXP, 1), 
           lag.education_EXP = lag(education_EXP, 1), 
           lag.health_EXP = lag(health_EXP, 1),
           lag.social_protection_EXP = lag(social_protection_EXP, 1),
           lag.housing_EXP = lag(housing_EXP, 1), 
           lag.owelfarespend_EXP = lag(owelfarespend_EXP, 1))

#calculate stability index
attach(dv2)
yb <- (expend_security_EXP - lag.expend_security_EXP)^2 +
     (expenddefence_EXP - lag.expenddefence_EXP)^2 +
     (exp_public_order_EXP - lag.exp_public_order_EXP)^2 +
     (total_welfare_EXP - lag.total_welfare_EXP)^2 +
     (education_EXP - lag.education_EXP)^2 +
     (health_EXP - lag.health_EXP)^2 +
     (social_protection_EXP - lag.social_protection_EXP)^2 +
     (housing_EXP - lag.housing_EXP)^2 +
     (owelfarespend_EXP - lag.owelfarespend_EXP)^2


#attach to data
mydata$stability_4_aj <- sqrt(yb)
#recode 0 to missing
mydata$stability_4_aj[mydata$stability_4_aj == 0] <- NA

#--------------------------------------------------------------------------
dv2 <- imp5
#replace NA to 0. 
dv2[is.na(dv2)] <- 0


#create lagged variable
dv2 <- 
    dv2 %>%
    group_by(cowcode) %>%
    mutate(lag.expend_security_EXP = lag(expend_security_EXP, 1), 
           lag.expenddefence_EXP = lag(expenddefence_EXP, 1),
           lag.exp_public_order_EXP = lag(exp_public_order_EXP, 1), 
           lag.total_welfare_EXP = lag(total_welfare_EXP, 1), 
           lag.education_EXP = lag(education_EXP, 1), 
           lag.health_EXP = lag(health_EXP, 1),
           lag.social_protection_EXP = lag(social_protection_EXP, 1),
           lag.housing_EXP = lag(housing_EXP, 1), 
           lag.owelfarespend_EXP = lag(owelfarespend_EXP, 1))

#calculate stability index
attach(dv2)
yb <- (expend_security_EXP - lag.expend_security_EXP)^2 +
     (expenddefence_EXP - lag.expenddefence_EXP)^2 +
     (exp_public_order_EXP - lag.exp_public_order_EXP)^2 +
     (total_welfare_EXP - lag.total_welfare_EXP)^2 +
     (education_EXP - lag.education_EXP)^2 +
     (health_EXP - lag.health_EXP)^2 +
     (social_protection_EXP - lag.social_protection_EXP)^2 +
     (housing_EXP - lag.housing_EXP)^2 +
     (owelfarespend_EXP - lag.owelfarespend_EXP)^2


#attach to data
mydata$stability_5_aj <- sqrt(yb)
#recode 0 to missing
mydata$stability_5_aj[mydata$stability_5_aj == 0] <- NA


#--------------------------------------------------------------------------
#export to doable file
write.csv(x = mydata, file = "mydata.csv", row.names = FALSE)
```


-->

